server:
  port: 8091
  servlet:
    context-path: /crud
  tomcat:
    uri-encoding: UTF-8

spring:
  messages:
    basename: i18n.login
  # 禁用缓存
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
